name: Build Fabric Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Build with Gradle
        run: gradle build

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: horrorsfromfog-jar
          path: build/libs/*.jar
